# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapmak.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(249, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(10, 80, 51, 41))
        self.btn1.setObjectName("btn1")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(10, 130, 51, 41))
        self.btn4.setObjectName("btn4")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(10, 180, 51, 41))
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(70, 180, 51, 41))
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(130, 180, 51, 41))
        self.btn9.setObjectName("btn9")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(130, 130, 51, 41))
        self.btn6.setObjectName("btn6")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(130, 80, 51, 41))
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(70, 80, 51, 41))
        self.btn2.setObjectName("btn2")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(70, 130, 51, 41))
        self.btn5.setObjectName("btn5")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(70, 230, 51, 41))
        self.btn0.setObjectName("btn0")
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setGeometry(QtCore.QRect(10, 230, 51, 41))
        self.btnDel.setObjectName("btnDel")
        self.btnEqual = QtWidgets.QPushButton(self.centralwidget)
        self.btnEqual.setGeometry(QtCore.QRect(130, 230, 51, 41))
        self.btnEqual.setObjectName("btnEqual")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(190, 80, 51, 41))
        self.btnAdd.setObjectName("btnAdd")
        self.btnSubs = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubs.setGeometry(QtCore.QRect(190, 130, 51, 41))
        self.btnSubs.setObjectName("btnSubs")
        self.btnMult = QtWidgets.QPushButton(self.centralwidget)
        self.btnMult.setGeometry(QtCore.QRect(190, 180, 51, 41))
        self.btnMult.setObjectName("btnMult")
        self.btnDiv = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiv.setGeometry(QtCore.QRect(190, 230, 51, 41))
        self.btnDiv.setObjectName("btnDiv")
        self.textAnsw = QtWidgets.QTextBrowser(self.centralwidget)
        self.textAnsw.setGeometry(QtCore.QRect(10, 20, 231, 51))
        self.textAnsw.setObjectName("textAnsw")
        self.btnAC = QtWidgets.QPushButton(self.centralwidget)
        self.btnAC.setGeometry(QtCore.QRect(10, 280, 51, 41))
        self.btnAC.setObjectName("btnAC")
        self.btnDot = QtWidgets.QPushButton(self.centralwidget)
        self.btnDot.setGeometry(QtCore.QRect(70, 280, 51, 41))
        self.btnDot.setObjectName("btnDot")
        self.btnUst = QtWidgets.QPushButton(self.centralwidget)
        self.btnUst.setGeometry(QtCore.QRect(130, 280, 51, 41))
        self.btnUst.setObjectName("btnUst")
        self.btnPi = QtWidgets.QPushButton(self.centralwidget)
        self.btnPi.setGeometry(QtCore.QRect(190, 280, 51, 41))
        self.btnPi.setObjectName("btnPi")
        self.btnPar1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnPar1.setGeometry(QtCore.QRect(10, 330, 51, 41))
        self.btnPar1.setObjectName("btnPar1")
        self.btnPar2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnPar2.setGeometry(QtCore.QRect(70, 330, 51, 41))
        self.btnPar2.setObjectName("btnPar2")
        self.btnKok = QtWidgets.QPushButton(self.centralwidget)
        self.btnKok.setGeometry(QtCore.QRect(130, 330, 51, 41))
        self.btnKok.setObjectName("btnKok")
        self.btnE = QtWidgets.QPushButton(self.centralwidget)
        self.btnE.setGeometry(QtCore.QRect(190, 330, 51, 41))
        self.btnE.setObjectName("btnE")
        self.lbASB = QtWidgets.QLabel(self.centralwidget)
        self.lbASB.setGeometry(QtCore.QRect(160, 380, 81, 16))
        self.lbASB.setObjectName("lbASB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 249, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnDel.setText(_translate("MainWindow", "DEL"))
        self.btnEqual.setText(_translate("MainWindow", "="))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.btnSubs.setText(_translate("MainWindow", "-"))
        self.btnMult.setText(_translate("MainWindow", "x"))
        self.btnDiv.setText(_translate("MainWindow", "/"))
        self.btnAC.setText(_translate("MainWindow", "AC"))
        self.btnDot.setText(_translate("MainWindow", "."))
        self.btnUst.setText(_translate("MainWindow", "^"))
        self.btnPi.setText(_translate("MainWindow", "Pi"))
        self.btnPar1.setText(_translate("MainWindow", "("))
        self.btnPar2.setText(_translate("MainWindow", ")"))
        self.btnKok.setText(_translate("MainWindow", "√"))
        self.btnE.setText(_translate("MainWindow", "e"))
        self.lbASB.setText(_translate("MainWindow", "Coded by ASB"))
